networks:
  zbxnet:
    external: true

services:
  # =========================
  # Zabbix Server DC2
  # =========================
  zbx-server-02:
    image: zabbix/zabbix-server-mysql:alpine-7.4-latest
    container_name: zbx-server-02
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: "10.7.0.10"          # VIP DB
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "abcdef"
      TZ: "Asia/Jakarta"
      # HA
      ZBX_HANODENAME: "DC2"
      ZBX_NODEADDRESS: "10.7.0.5:10051"
    networks:
      - zbxnet
    ports:
      - "10051:10051"
    cap_add:
      - NET_RAW
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "pgrep", "zabbix_server"]
      interval: 10s
      timeout: 5s
      retries: 5

  # =========================
  # Zabbix Frontend DC2
  # =========================
  zbx-frontend:
    image: zabbix/zabbix-web-nginx-mysql:alpine-7.4-latest
    container_name: zbx-frontend
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: "10.7.0.10"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "abcdef"
      PHP_TZ: "Asia/Jakarta"
    networks:
      - zbxnet
    ports:
      - "8080:8080"
    depends_on:
      - zbx-server-02
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "pgrep", "php-fpm"]
      interval: 10s
      timeout: 5s
      retries: 5
