services:
  # One-shot init job: import schema/images/data kalau DB masih kosong
  zbx-db-init:
    image: zabbix/zabbix-server-mysql:alpine-7.0-latest
    container_name: zbx-db-init
    environment:
      DB_SERVER_HOST: ${DB_SERVER_HOST}
      DB_SERVER_PORT: ${DB_SERVER_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}
      FORCE_REIMPORT: ${FORCE_REIMPORT:-0}
    entrypoint: ["/bin/sh","-lc"]
    command: >
      set -e;
      echo "[zbx-db-init] Waiting DB ${DB_SERVER_HOST}:${DB_SERVER_PORT}";
      until mysql -h${DB_SERVER_HOST} -P${DB_SERVER_PORT} -u${MYSQL_USER} -p${MYSQL_PASSWORD} -e "SELECT 1" ${MYSQL_DATABASE} >/dev/null 2>&1; do
        sleep 2; echo -n .; done; echo;
      cnt=$$(mysql -N -h${DB_SERVER_HOST} -P${DB_SERVER_PORT} -u${MYSQL_USER} -p${MYSQL_PASSWORD}
        -e "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='${MYSQL_DATABASE}'");
      echo "[zbx-db-init] Tables in ${MYSQL_DATABASE}: $$cnt";
      if [ "${FORCE_REIMPORT}" = "1" ]; then cnt=0; fi;
      if [ "$$cnt" -lt 10 ]; then
        echo "[zbx-db-init] Importing schema...";
        zcat /usr/share/doc/zabbix-sql-scripts/mysql/schema.sql.gz | \
          mysql -h${DB_SERVER_HOST} -P${DB_SERVER_PORT} -u${MYSQL_USER} -p${MYSQL_PASSWORD} ${MYSQL_DATABASE};
        echo "[zbx-db-init] Importing images...";
        zcat /usr/share/doc/zabbix-sql-scripts/mysql/images.sql.gz | \
          mysql -h${DB_SERVER_HOST} -P${DB_SERVER_PORT} -u${MYSQL_USER} -p${MYSQL_PASSWORD} ${MYSQL_DATABASE};
        echo "[zbx-db-init] Importing data...";
        zcat /usr/share/doc/zabbix-sql-scripts/mysql/data.sql.gz | \
          mysql -h${DB_SERVER_HOST} -P${DB_SERVER_PORT} -u${MYSQL_USER} -p${MYSQL_PASSWORD} ${MYSQL_DATABASE};
        echo "[zbx-db-init] Done.";
      else
        echo "[zbx-db-init] Database already initialized; skip.";
      fi
    restart: "no"
    networks: [zbx_net]

  zabbix-server:
    build:
      context: .
      dockerfile: ./Dockerfile.server
    container_name: zbx-server-dc1
    depends_on:
      - zbx-db-init
    environment:
      DB_SERVER_HOST: ${DB_SERVER_HOST}
      DB_SERVER_PORT: ${DB_SERVER_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ZBX_DEBUGLEVEL: ${ZBX_DEBUGLEVEL}
      TZ: ${TZ}
    ports:
      - "10051:10051"
    volumes:
      - zbx_srv_data:/var/lib/zabbix
      - zbx_srv_log:/var/log/zabbix
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    networks: [zbx_net]

  zabbix-web:
    build:
      context: .
      dockerfile: ./Dockerfile.web
    container_name: zbx-web-dc1
    depends_on:
      - zabbix-server
    environment:
      DB_SERVER_HOST: ${DB_SERVER_HOST}
      DB_SERVER_PORT: ${DB_SERVER_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: ${TZ}
      TZ: ${TZ}
    ports:
      - "${HTTP_PORT}:8080"
    volumes:
      - zbx_web_log:/var/log/nginx
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    networks: [zbx_net]

networks:
  zbx_net:
    name: zbx_net

volumes:
  zbx_srv_data:
  zbx_srv_log:
  zbx_web_log: