version: '3.5'

services:
  # =========================
  # Zabbix Server (failover HA)
  # =========================
  zabbix-server:
    image: zabbix/zabbix-server-mysql:ubuntu-7.4-latest
    container_name: zbx-server
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: "10.7.0.10"      # VIP MySQL dari Keepalived
      DB_SERVER_PORT: "3306"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "abcdef"
      MYSQL_DATABASE: "zabbix"
      TZ: "Asia/Jakarta"
      ZBX_HANODENAME: "${HOSTNAME}"    # Nama node HA (beda di DC1 & DC2)
    ports:
      - "10051:10051"                  # Zabbix Server trapper port
    networks:
      - zbx-net
    cap_add:
      - NET_RAW                         # supaya fping jalan untuk ICMP ping

  # =========================
  # Zabbix Web (Frontend)
  # =========================
  zabbix-web:
    image: zabbix/zabbix-web-apache-mysql:ubuntu-7.4-latest
    container_name: zbx-web
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: "10.7.0.10"
      DB_SERVER_PORT: "3306"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "abcdef"
      MYSQL_DATABASE: "zabbix"
      PHP_TZ: "Asia/Jakarta"
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - zbx-net

networks:
  zbx-net:
    driver: bridge
