FROM zabbix/zabbix-web-nginx-mysql:alpine-6.4-latest

LABEL maintainer="Andes Solutions"

USER root
RUN apk add --no-cache bash curl vim iputils bind-tools net-tools iproute2 tcpdump
USER zabbix

EXPOSE 8080
CMD ["docker-entrypoint.sh"]
