networks:
  zbxnet:
    external: true

services:
  zbx-server:
    image: zabbix/zabbix-server-mysql:alpine-7.4-latest
    container_name: zbx-server
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: "10.7.0.10"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "abcdef"
      MYSQL_ROOT_PASSWORD: "abcdef"
      TZ: "Asia/Jakarta"
      ZBX_NODE_NAME: "DC1"      # ⬅️ Nama unik node HA
    networks:
      - zbxnet
    ports:
      - "10051:10051"
    cap_add:
      - NET_RAW
    healthcheck:
      test: ["CMD", "pgrep", "zabbix_server"]
      interval: 10s
      timeout: 5s
      retries: 5

  zbx-frontend:
    image: zabbix/zabbix-web-nginx-mysql:alpine-7.4-latest
    container_name: zbx-frontend
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: "10.7.0.10"        # DC1 → mysql1, DC2 → mysql2
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "abcdef"
      PHP_TZ: "Asia/Jakarta"
      ZBX_SERVER_HOST: "zbx-server"   # ⬅️ tambahin ini
      ZBX_SERVER_PORT: "10051"        # ⬅️ opsional (default 10051)
    networks:
      - zbxnet
    depends_on:
      - zbx-server
    ports:
      - "8080:8080"

