networks:
  zbxnet:
    external: true

services:
  zbx-server:
    image: zabbix/zabbix-server-mysql:alpine-7.4-latest
    container_name: zbx-server
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: "10.7.0.10"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "abcdef"
      MYSQL_ROOT_PASSWORD: "abcdef"
      TZ: "Asia/Jakarta"
      # === HA ===
      ZBX_HANODENAME: "DC2"
      ZBX_NODEADDRESS: "10.7.0.5:10051"
    networks:
      - zbxnet
    ports:
      - "10051:10051"
    cap_add:
      - NET_RAW
    healthcheck:
      test: ["CMD", "pgrep", "zabbix_server"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- Zabbix Frontend @ DC2 ---
  zbx-frontend:
    image: zabbix/zabbix-web-nginx-mysql:alpine-7.4-latest
    container_name: zbx-frontend
    restart: unless-stopped
    environment:
      # koneksi DB (VIP)
      DB_SERVER_HOST: "10.7.0.10"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "abcdef"
      # zona waktu PHP
      PHP_TZ: "Asia/Jakarta"
      # ❗ Jangan set ZBX_SERVER_HOST / ZBX_SERVER_PORT pada mode HA
    networks:
      - zbxnet
    # opsional: kalau frontend mau dipublikasikan dari DC2
    ports:
      - "8080:8080"
    # opsional: tunggu server jika di file ini ada service zbx-server
    depends_on:
      - zbx-server
    healthcheck:
      test: ["CMD", "pgrep", "php-fpm"]
      interval: 10s
      timeout: 5s
      retries: 5

