# Zabbix Server (MySQL) — Zabbix 7.0 Alpine
FROM zabbix/zabbix-server-mysql:alpine-7.0-latest

USER root
RUN apk add --no-cache bash tzdata curl mysql-client \
  && cp /usr/share/zoneinfo/Asia/Jakarta /etc/localtime \
  && echo "Asia/Jakarta" > /etc/timezone

ADD ./healthcheck-server.sh /usr/local/bin/healthcheck-server.sh
RUN chmod +x /usr/local/bin/healthcheck-server.sh

HEALTHCHECK --interval=20s --timeout=10s --retries=6 \
  CMD /usr/local/bin/healthcheck-server.sh
