  # === MySQL DC2 ===
  mysql2:
    build:
      context: ../mysql
      dockerfile: Dockerfile
    container_name: mysql2
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "AndesMysql123!"
    volumes:
      - /opt/mysql:/var/lib/mysql
      - ../mysql/my.cnf.dc2:/etc/mysql/conf.d/my.cnf
      - ../mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
      - "33061:33061"   # 👈 tambahkan ini
