version: "3.9"

services:
  # =========================
  # MySQL DC1 (10.7.0.4)
  # =========================
  mysql1:
    build:
      context: ../mysql
      dockerfile: Dockerfile
    container_name: mysql1
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "abcdef"
      TZ: "Asia/Jakarta"
    volumes:
      - /opt/mysql:/var/lib/mysql
      - ../mysql/my.cnf.dc1:/etc/mysql/conf.d/my.cnf:ro
      - ../mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ../mysql/dc1.sql:/docker-entrypoint-initdb.d/dc1.sql:ro 
    # HANYA expose 3306 (tidak pakai host network)
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uroot -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 3s
      retries: 20

  # =========================
  # Zabbix Server DC1
  # =========================
  zabbix-server:
    build:
      context: ../zabbix
      dockerfile: Dockerfile.server
    container_name: zbx-server-dc1
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: "10.7.0.10"     # VIP DB (ikut failover)
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "AndesZabbix!"
      HANodeName: "dc1"
      TZ: "Asia/Jakarta"
    # publish ke host agar HAProxy (host net) bisa forward ke 127.0.0.1:10051
    ports:
      - "10051:10051"
    depends_on:
      - mysql1
    healthcheck:
      test: ["CMD-SHELL", "timeout 3 bash -lc '</dev/tcp/127.0.0.1/10051' || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 30

  # =========================
  # Zabbix Web DC1
  # =========================
  zabbix-web:
    build:
      context: ../zabbix
      dockerfile: Dockerfile.web
    container_name: zbx-web-dc1
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: "10.7.0.10"     # VIP DB
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "AndesZabbix!"
      ZBX_SERVER_HOST: "zbx-server-dc1"
      PHP_TZ: "Asia/Jakarta"
    ports:
      - "8080:8080"                   # HAProxy konsumsi di 127.0.0.1:8080
    depends_on:
      - zabbix-server
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8080/ || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 30