version: '3'

networks:
  zabbix_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.11.12.0/24

services:
  mysql1:
    image: mysql:8.0.30
    container_name: mysql1
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "AndesMysql123!"
    volumes:
      - /opt/mysql:/var/lib/mysql
      - ../mysql/my.cnf.dc1:/etc/mysql/conf.d/my.cnf
      - ../mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      zabbix_net:
        ipv4_address: 10.11.12.2