version: '3.8'

services:
  haproxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: haproxy-hub
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
